name: mobile-ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      - name: Install
        run: npm ci
      - name: Lint
        run: |
          if [ -f package.json ] && jq -e '.scripts.lint' package.json > /dev/null; then npm run lint; else echo "No lint script"; fi
      - name: Test
        run: |
          if [ -f package.json ] && jq -e '.scripts.test' package.json > /dev/null; then npm test -- --ci; else echo "No test script"; fi
